# Generated by Django 2.2.6 on 2020-06-05 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512, verbose_name='Título')),
                ('enlace', models.URLField(validators=[django.core.validators.URLValidator()], verbose_name='Enlace')),
                ('autor', models.CharField(max_length=512, verbose_name='Autor')),
                ('fechaHora', models.DateTimeField(verbose_name='Fecha y hora')),
            ],
        ),
    ]
