# Generated by Django 2.2.6 on 2020-05-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionVinos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vino',
            name='puntuacion',
        ),
        migrations.AddField(
            model_name='vino',
            name='estrellas',
            field=models.DecimalField(decimal_places=1, max_digits=10, null=True, verbose_name='Estrellas'),
        ),
        migrations.AlterField(
            model_name='vino',
            name='precio',
            field=models.CharField(max_length=1024, verbose_name='Precio'),
        ),
    ]
