# Generated by Django 2.2.6 on 2020-05-25 17:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField()),
                ('titulo', models.CharField(max_length=512)),
                ('autor', models.CharField(max_length=512)),
                ('añoPublicacion', models.CharField(max_length=512)),
                ('editor', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.IntegerField()),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('isbn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionLibros.Libro')),
            ],
        ),
    ]
