# Generated by Django 2.2.6 on 2020-05-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
