# Generated by Django 2.2.6 on 2020-05-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0002_auto_20200525_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='puntuacion',
            name='isbn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gestionLibros.Libro'),
        ),
    ]
