# Generated by Django 2.2.6 on 2020-05-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionLibros', '0006_auto_20200525_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='isbn',
            field=models.IntegerField(),
        ),
    ]
