# Generated by Django 2.2.6 on 2020-05-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=256, verbose_name='Título')),
                ('autor', models.CharField(max_length=256, verbose_name='Autor')),
                ('fuenteNoticia', models.CharField(max_length=256, null=True, verbose_name='Fuente')),
                ('fechaYHora', models.DateTimeField(verbose_name='Fecha y hora')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('numeroComentario', models.IntegerField(verbose_name='Número de comentarios')),
            ],
        ),
    ]
