# Generated by Django 2.2.6 on 2020-06-01 15:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('formatoEmision', models.CharField(max_length=512)),
                ('numeroEpisodios', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Puntuacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('idAnime', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAnimes.Anime')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gestionAnimes.Usuario')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='generos',
            field=models.ManyToManyField(to='gestionAnimes.Genero'),
        ),
    ]
