# Generated by Django 2.2.6 on 2020-06-01 11:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512, verbose_name='Nombre')),
                ('url', models.URLField(validators=[django.core.validators.URLValidator()])),
                ('pictureUrl', models.URLField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagValue', models.CharField(max_length=512, verbose_name='TagValue')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEtiquetaArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('año', models.IntegerField(max_length=4, verbose_name='Año')),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionArtistas.Artista')),
                ('idTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionArtistas.Etiqueta')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionArtistas.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempoEscucha', models.IntegerField(verbose_name='TiempoEscucha')),
                ('idArtista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionArtistas.Artista')),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionArtistas.Usuario')),
            ],
        ),
    ]
